version: '3'
services:
  app:
    build: .
    ports:
      - "8600:3000"
    environment:
      - FLAG=zer0pts{fire_ice_storm_di_acute_brain_damned_jugem_bayoen_bayoen_bayoen_10cefab0}
    restart: always