version: "3.9"

services:
  app:
    build: ./app
    container_name: flask_app
    restart: always
    networks:
      - app_net

  nginx:
    image: nginx:1.22.0
    container_name: nginx_proxy
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
